# Generated by Django 3.2 on 2023-02-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_item_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_id',
        ),
    ]
