# Generated by Django 3.2 on 2023-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='payment.OrderItem', to='payment.Item'),
        ),
    ]
