# Generated by Django 3.2 on 2023-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='payment.Item'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]


